### PR TITLE
Add Appengine source example

### PR DESCRIPTION
**Pull request by tikasan**
I created an example that actually works.
If there is a missing part, please propose a suggestion.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you! the only thing I'm wondering is whether we could avoid pushing `glide.lock`. The dependencies are going to become stale very quick otherwise.

**Comment by tikasan** [comment]
ok.
I decided to delete glide.lock.

**Comment by raphael** [comment]
Thank you, looks great! One last thing I promise :-) Could you update the `README` with instructions on how to compile, deploy and run the example? (e.g. setup appengine project, replace project name in makefile, run `make` ...)

**Comment by tikasan** [comment]
I added it.

**Comment by raphael** [comment]
Thank you!

**Comment by raphael** [comment]
FYI I tweaked the README a bit to add some more information: https://github.com/goadesign/examples/commit/87eaf7b32db885cfa74129f775996fb977a76cee

**Comment by tikasan** [comment]
Thank you for fixing!

**Pull request merged**
