### PR TITLE
Suppress staticcheck rule that is causing build failure.

### LINKED ISSUE #51: Build failure due to new version of staticcheck
Staticcheck added ST1021 which confirms the first word in a type comment matches the name of the type. This check should be disabled until the goa code generation templates are updated to conform with this validation.

https://github.com/dominikh/go-tools/commit/2c70f907df0394e2fc6c63b04fdfd5890f5a260d

Current lint target fails with:
```
make lint
LINTING CODE...
basic/gen/calc/service.go:15:1: comment on exported type Service should be of the form "Service ..." (with optional leading article) (ST1021)
cellar/gen/sommelier/service.go:17:1: comment on exported type Service should be of the form "Service ..." (with optional leading article) (ST1021)
cellar/gen/sommelier/service.go:83:1: comment on exported type NoCriteria should be of the form "NoCriteria ..." (with optional leading article) (ST1021)
cellar/gen/sommelier/service.go:86:1: comment on exported type NoMatch should be of the form "NoMatch ..." (with optional leading article) (ST1021)
cellar/gen/storage/service.go:17:1: comment on exported type Service should be of the form "Service ..." (with optional leading article) (ST1021)
...
```

### PR DESCRIPTION
**Pull request by eric-isakson**
Fixes #51

### CODE REVIEW

**Comment by eric-isakson** [comment]
Looks like this will need to be rebased on top of a change to update the generated examples to v3.0.3

**Comment by eric-isakson** [comment]
I'm not able to repeat the problem in my local build which is using the v3.0.3 in the header comment. Any ideas? Maybe something incorrectly cached in the travis build?

**Comment by raphael** [comment]
Yes it was the cache :( - I think we should remove `HOME/.cache/go-build` from the list of cached directories in the travis config. Would you care to add a commit that did that to this PR? thank you!

**Comment by eric-isakson** [comment]
Sorry, I did a forced push with an amended commit, not sure if I hosed things up...I'm not used to the PR model as I use gerrit normally so amending is my normal mode. If you need me to redo the PR, let me know.

**Comment by eric-isakson** [comment]
Too much context switching for me with other work, I missed the git add and didn't actually get the travis.yml change in that earlier commit...should be good now. Sorry for the noise.

**Comment by raphael** [comment]
No worries, thank you for the fix!

**Pull request merged**
