### PR TITLE
Update security/auth.go to implement Auther interface

### PR DESCRIPTION
**Pull request by tchssk**
This is a backport of #54 to v2.

### CODE REVIEW

**Comment by raphael** [comment]
Thank you for the fix! looks like there's a formatting issue in the file?

**Comment by tchssk** [comment]
We need a new tag for v2 to success a build on CI because goa is referenced via https://gopkg.in/goadesign/goa.v2.

**Comment by raphael** [comment]
OK would be good to fix the build before tagging, looks like the examples are not in sync.

**Comment by raphael** [comment]
Is this PR still needed or can it be closed?

**Comment by tchssk** [comment]
I'll open a new pull request.

**Pull request closed without merging**
